/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-6h3Z2JxTFMUvYgA3hJ-TZvszdFgC-nEmmHstthKGmzjrMcBrqD9WIz5vajx63DTTyeTAIpUd4YNtvjHYpsk9F-BWxWZGIcsbUR-G4mApb7skiHQDx4eYx-yG",
  "tt": "tt-1-D9wtCSam8PcK4n4huN8HPCXIY1T4ulZx-cLkKAQBVGw=",
  "version": "2020-11-20"
}

export default ebconfig;